# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0002_auto_20190311_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.IntegerField(choices=[(1, b'Low'), (2, b'Medium'), (3, b'High')], default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
