# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0003_auto_20190312_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='personal_due_date',
            field=models.DateField(),
        ),
    ]
