# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0006_auto_20190312_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to=b'category-images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=b'profile-images/default.png', upload_to=b'profile-images/'),
        ),
    ]
