# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskdesk', '0007_auto_20190312_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('user', 'category_name')]),
        ),
    ]
