# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0008_auto_20190312_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=45),
        ),
    ]
