# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0010_auto_20190313_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='personal_due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
