# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0012_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
