# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0013_remove_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='high_priority_color',
            field=models.CharField(default=b'#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='low_priority_color',
            field=models.CharField(default=b'#00FF00', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medium_priority_color',
            field=models.CharField(default=b'#FFA500', max_length=7),
        ),
    ]
