# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0014_auto_20190316_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default=b'profile-images/default.png', upload_to=b'profile-images/'),
        ),
    ]
