# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdesk', '0016_auto_20190316_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
